// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMq0CXnGHXiU3__wjCRDH416qafV5S_9w',
    appId: '1:154830469928:web:cebcb4d49cd936d9766e1d',
    messagingSenderId: '154830469928',
    projectId: 'my-first-app-a2d73',
    authDomain: 'my-first-app-a2d73.firebaseapp.com',
    storageBucket: 'my-first-app-a2d73.appspot.com',
    measurementId: 'G-5M2LT8XY7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTxvikDfxJNX79KNORGPJ_f5tl81X3qU0',
    appId: '1:154830469928:android:9f1d210fd5b7c514766e1d',
    messagingSenderId: '154830469928',
    projectId: 'my-first-app-a2d73',
    storageBucket: 'my-first-app-a2d73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtO9FpO2TkP63_yUG9QCeGXonU7mOIHs0',
    appId: '1:154830469928:ios:52799d6c9b56f7dc766e1d',
    messagingSenderId: '154830469928',
    projectId: 'my-first-app-a2d73',
    storageBucket: 'my-first-app-a2d73.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtO9FpO2TkP63_yUG9QCeGXonU7mOIHs0',
    appId: '1:154830469928:ios:52799d6c9b56f7dc766e1d',
    messagingSenderId: '154830469928',
    projectId: 'my-first-app-a2d73',
    storageBucket: 'my-first-app-a2d73.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMq0CXnGHXiU3__wjCRDH416qafV5S_9w',
    appId: '1:154830469928:web:06c55509e4dfb5f0766e1d',
    messagingSenderId: '154830469928',
    projectId: 'my-first-app-a2d73',
    authDomain: 'my-first-app-a2d73.firebaseapp.com',
    storageBucket: 'my-first-app-a2d73.appspot.com',
    measurementId: 'G-V3YQN636PC',
  );

}